### ISSUE TITLE
MRAN link broken in rocker/tidyverse:3.5.1. Consider providing a backup repository?

### ISSUE THREAD

**Issue by ashiklom** [rocker-org/rocker-versioned#102]
There seems to be an issue with the MRAN September 1, 2018 snapshot.

I launch an image as follows:

```
docker run -it --rm rocker/tidyverse:3.5.1 R
```

Then, if I try to install a package using `install.packages`, I get...

```
install.packages("dplyr")
# Installing package into ‘/usr/local/lib/R/site-library’
# (as ‘lib’ is unspecified)
# Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2018-09-01/src/contrib:
#  cannot open URL 'https://mran.microsoft.com/snapshot/2018-09-01/src/contrib/PACKAGES'
# Warning message:
# package ‘dplyr’ is not available (for R version 3.5.1)
```

(This is a test case. I'm aware that `tidyverse` includes `dplyr` already.)

The link to the snapshot itself works fine, albeit with a redirect (replace `mran` with `cran`): https://mran.microsoft.com/snapshot/2018-09-01

...but the the full link to the `PACKAGES` file is in fact broken: https://mran.microsoft.com/snapshot/2018-09-01/src/contrib/PACKAGES

Pointing to a different remote (e.g. `https://cran.rstudio.org`) installs the package just fine.

I know this probably isn't your guys' fault and is a problem on Microsoft's end. But, in case this crops up in the future, would it make sense to add a different CRAN mirror as a backup? Providing a vector of repositories seems to behave as expected, with R trying the first repository first and then falling back on the second one if it fails:

```
install.packages("dplyr", repos = c("https://mran.microsoft.com/snapshot/2018-09-01", "https://cran.rstudio.org"))
```

**Comment by cboettig** [comment]
@ashiklom 

Yes, it does look like Microsoft's snapshot is down for the moment; we'll give them a ping.  

But it also sounds like you might want to be using the `latest` tag and not the `3.5.1` tag.  Please note that MRAN provides a fixed snapshot so that you get the same version of the software every time, it is not just another CRAN mirror.  This point is somewhat moot when using the tag that matches the latest version; and perhaps we should re-consider that behavior.  But once a version is not the latest, we have to install from MRAN and not CRAN because the versions of software on CRAN can change every day, whereas the MRAN snapshot mirror always provides the same version.  

If you just want the latest stuff from CRAN, you'll get that (along with the default CRAN mirror already pointing to https://cran.rstudio.org) if you use the `latest` tag.  By specifying a version in your tag, you're signaling that you want a specific version of everything, and thus it is necessary to point to a snapshot mirror.  Microsoft has been pretty good about snapshotting CRAN every single day for the past six-odd years and keeping all those snapshots up, but not perfect.

**Comment by ashiklom** [comment]
Thanks for the quick reply! After posting this, I saw the earlier related issue (#58) and Tweeted a reply to that thread to notify them.

My use of `3.5.1` here was somewhat deliberate -- I wanted to have access to the latest R package updates up until the release of 3.5.2, at which point the packages would freeze, giving us a chance to re-evaluate if everything still works with 3.5.2 before upgrading the stack (that's how it works, right?). But maybe that's not a good idea.

Re: Adding CRAN as a backup -- My point was just that, if MRAN snapshots have a history of periodically (albeit rarely) breaking, it might not be a bad idea to have a backup repository so builds don't suddenly and somewhat mysteriously break whenever Microsoft has a hiccup. Doesn't have to be (and probably _shouldn't_ be) the latest CRAN. Arguably a better idea would be an older CRAN snapshot from Microsoft or elsewhere, so that you have access to at least a reasonably recent version of a package if you're not too picky about versions. As I mentioned, I don't think it should be too hard to add that safeguard -- just a matter of adding a second `repos`, which I _think_ should just act as a fallback (unless `install.packages` does some kind of weird vector recycling of the `pkg` and `repos` arguments -- I sure hope not!).

But anyway, thanks for all your work maintaining these images! You guys are doing a huge service to the open-source community 😄

**Comment by ashiklom** [comment]
Point taken, thanks for the reply! Feel free to close this issue (or wait until MRAN is back up, so it's easy to find if others come looking).

For the sake of documentation, a quick-and-very-dirty temporary workaround (_not a permanent solution!_) for anyone interested in quickly getting things running again without worrying too much about reproducibility is to insert a line like the following in a Dockerfile prior to any `install.packages` calls (just don't forget to remove it once things are back to normal!):

```
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.org'))" >> /usr/local/lib/R/etc/Rprofile.site
```

**Comment by cboettig** [comment]
Thanks!

**Comment by reganchan** [comment]
I'm using tidyverse:latest. Somehow it still uses MRAN and MRAN is today, again. Can the MRAN repo be permanently removed?
