### ISSUE TITLE
Automatically setting Rstudio theme fails on latest build

### ISSUE THREAD

**Issue by tomwallis** [rocker-org/rocker-versioned#107]
I used the tip from [here](http://www.derekmpowell.com/posts/2018/02/docker-tutorial-3/) to automatically set my Rstudio theme when running a docker container. Specifically, my Dockerfile contained:

`COPY set_theme.sh /etc/cont-init.d/theme`

and `set_theme.sh` contained

```
!/usr/bin/with-contenv bash

THEME=${THEME:=none}

if [ "$THEME" != none ]; then
	mkdir -p /home/rstudio/.rstudio/monitored/user-settings
	echo "uiPrefs={\"theme\" : \"$THEME\"}" > \
	/home/rstudio/.rstudio/monitored/user-settings/user-settings
	chown -R rstudio /home/rstudio
fi
```

This worked fine when building from versioned images up to `3.5.1`. 

However, I've just started using the `latest` build in order to resolve [this issue](http://github.com/rocker-org/rocker-versioned/issues/104), which I also had. It may be that @cboettig's resolution [here](https://github.com/rocker-org/rocker-versioned/issues/104#issuecomment-432000320) has changed how the above theme hack behaves. 

Specifically, if I include the `COPY` line above in my Dockerfile, the build succeeds but the container crashes after being run. I don't see any error message (sorry, very new to Docker) but basically I get a hash return after `docker run`, but the container disappears from `docker container ls` after a few seconds and the port is closed. Removing the `COPY` line from the Dockerfile makes the container work fine.

I assume this is something about the permission-setting step in the `set_theme.sh` file. I've tried 
`chown -R rstudio:staff /home/rstudio` and `chown -R root:staff /home/rstudio` but these don't seem to change the behaviour.

Could anyone suggest either

1. How to fix this issue 

or

2. A more robust way to automatically set the theme in RStudio running within a docker container?

This is no big deal, but if you see the obvious solution I'd appreciate help :)

**Comment by cboettig** [comment]
Thanks for the bug report.  Hmm, not sure why the previous solution is not working.   But note that `/home/rstudio/.rstudio/monitored/user-settings/user-settings` already exists and has [other settings](https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/Dockerfile#L79-L83) in it, so you can drop the `mkdir` part and you probably want `>>` to append.  `chown` also shouldn't be needed.  


If you're always setting the same theme for a custom dockerfile, I would hardwire the theme like so:

```
FROM rocker/rstudio

RUN echo "uiPrefs={\"theme\" : \"Solarized Dark\"}" >> \
  /home/rstudio/.rstudio/monitored/user-settings/user-settings
```

since I don't want more to type any more env vars run-time anyway.   🙃 

For most casual users wanting to customize the theme, it's probably easier to wait until RStudio comes up and just select the theme.  It will persist as long as the user-settings directory persists. (e.g. some folks volume link `~/.rstudio` to persist between container sessions).

**Comment by tomwallis** [comment]
Thanks for the quick reply! The solutions you've offered are all much better than the one I was using. Would you like to close the issue or check anything about permissions?

**Comment by cboettig** [comment]
👍 that's great to hear!  let's close this out then.
