### ISSUE TITLE
Error in library(httr) : there is no package called ‘httr’

### ISSUE THREAD

**Issue by sfahad1414** [rocker-org/rocker-versioned#115]
Even after installing the httr getting following error
Error in library(httr) : there is no package called ‘httr’
Calls: plumb ... <Anonymous> -> source -> withVisible -> eval -> eval -> library

**Comment by cboettig** [comment]
Please provide more information as to what image you have used and how you have attempted to install the package.  Also note that `httr` is already pre-installed on the `tidyverse` images; e.g.:

```
docker run --rm -ti rocker/tidyverse R
library(httr)
```

runs without error.

**Comment by cboettig** [comment]
@sfahad1414 Thanks for providing these details.  Why are you trying to install `httr` over apt-get instead of the way you have used for all the other packages?  We don't recommend installing R packages by apt-get on the versioned stack, see  README. https://github.com/rocker-org/rocker-versioned#notes .  If you use `install.packages()` I think you will find it works as expected.  

Also note that `httr` (and also `dplyr`) are already installed on the image you are starting with, so need to install them again.
