### ISSUE TITLE
auth-minimum-user-id=499 on unRAID

### ISSUE THREAD

**Issue by drdebian** [rocker-org/rocker-versioned#131]
It seems to be impossible for me to use this docker container on unRAID properly, since it would have to run as USERID=99, in order for permissions not to get messed up on files changed on the host by RStudio.

Lowering the setting in /etc/rserver/rserver.conf to 99 does not help, since it won't even let Rserver start anymore.

Is there any way to make this work with USERID=99?

**Comment by cboettig** [comment]
@drdebian Thanks for the note!  Unfortunately, I think we really need more information on what you're trying to do.  It sounds like you have a permissions issue because you are binding some volumes from the container directly to volumes on the host, but you haven't told us what. There are many different patterns for sharing data with the host machine, or otherwise having data persist separately from the rocker container, see https://docs.docker.com/storage/, which may include various strategies to work around the issues you are running into.  Hope this helps!

**Comment by drdebian** [comment]
Thanks for the prompt reply. The user ID issue arises from the fact that on unRAID, it is recommended to bind all volumes using the nobody user (ID 99) and the users group (ID 100), in order to not mess up permissions in the authentication layers above.

The volumes I'm binding are shares containing configs (/mnt/user/appdata/rstudio -> /home/rstudio) and projects (/mnt/user/rstudio -> /home/rstudio/projects). When going with the defaults of 1000:1000, on unRAID this would mean that the files would be accessible to only that one user, which prevents sharing the data using NFS and SMB effectively.

Being able to share data (in and out) as well as R code is rather important to enable collaboration across the network for me. Of course, unRAID's poor choice of low user IDs isn't helping the matter in this particular case. So my question is whether it would be possible to do away with the id<499 limitation (or make it configurable) or whether this will never happen because it would break things for everybody else.

**Comment by cboettig** [comment]
thanks for the details.  I don't think RStudio Server permits doing it this way, though you'd have to follow up with them on that; but that sounds specific to RStudio Server and independent of whether you're doing this from a rocker container or not I think.  

Still, there's lots of options here for persisting data.  You might consider binding your data volumes to somewhere else than under `/home/rstudio` in the container and let the user store their data there instead of working under `~/` directly.  

As I mention above, there's a wealth of information on how to manage persistent data in Docker, including working with NFS (e.g. see [docker-compose docs](https://docs.docker.com/compose/compose-file/#driver_opts).  Generally Docker strongly advises users to use Docker volumes to manage persistent data, since among other things adding that abstraction layer can mitigate a lot of these permission issues.  I'm not really an expert on the ever-growing collection of approaches, but the general Docker forums / stackoverflow etc have a lot on this stuff already.  best of luck!
