### ISSUE TITLE
current rstudio version reported by RStudio's current.ver is incorrect?

### ISSUE THREAD

**Issue by daroczig** [rocker-org/rocker-versioned#133]
```
wget -qO- https://s3.amazonaws.com/rstudio-server/current.ver 
```

returns

```
1.2.1335-1
```

And 

```
wget -q http://download2.rstudio.org/rstudio-server-${RSTUDIO_VERSION}-amd64.deb
```

fails with 404 due to the `-1` suffix.

**Comment by eddelbuettel** [comment]
Ok. So why report this here?  

We're clients of the side as you are.  Someone presumably needs to talk to RStudio, not us, no?

**Comment by daroczig** [comment]
Reported here as I think this is failing the `rstudio` Docker img builds, so this is a `rocker` issue. I understand this issue was caused by some changes by RStudio, so I'll contact them referencing this issue.

**Comment by cboettig** [comment]
Thanks @daroczig for the report! Yeah, I saw the last 2 nightly builds of rstudio failing, but hadn't tracked down why yet.  Of course we can hack around this if necessary but it would be nice for RStudio to fix it upstream, everything else refers to the version as `1.2.1335` so the `-1` suffix seems off.  

Maybe @kevinushey has some insight on this?

**Comment by jmcphers** [comment]
`current.ver` contains the RStudio Pro version number, which in RStudio 1.2 includes a suffix indicating its offset from the RStudio open source version number.

It sounds like what you want is the open source version, so I'd suggest removing the hyphen and any digits that follow it to derive it from the Pro version.

**Comment by daroczig** [comment]
Thanks, @jmcphers -- that's very useful to know!

Unfortunately, this approach suggests to get version `1.2.1335`, but http://download2.rstudio.org/rstudio-server-1.2.1335-amd64.deb is also 404, while it used to work ~48 hrs ago with http://download2.rstudio.org/rstudio-server-1.1.463-amd64.deb (that latter link still works).

**Comment by daroczig** [comment]
Oh, the correct URL for 1.2.1335 seems to be https://download2.rstudio.org/server/trusty/amd64/rstudio-server-1.2.1335-amd64.deb  -- @jmcphers, can you please confirm that from now on we should always include the `trusty/amd64` folders in the path?

**Comment by cboettig** [comment]
@daroczig I believe RStudio now provides more flavors of linux binary than it used to do.  I believe we should be getting: 

https://download1.rstudio.org/desktop/debian9/x86_64/rstudio-1.2.1335-amd64.deb

since we're building on `debian:9`.  I wouldn't be surprised if the `trusty` version works though.

**Comment by daroczig** [comment]
Ah, right, so something like

```
RSTUDIO_LATEST=$(wget --no-check-certificate -qO- https://s3.amazonaws.com/rstudio-server/current.ver | sed -e "s/-[0-9]*$//")
[ -z "$RSTUDIO_VERSION" ] && RSTUDIO_VERSION=$RSTUDIO_LATEST || true
wget -q http://download2.rstudio.org/server/debian9/amd64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb
```

But I'd suggest waiting for an official confirmation on this so that we can expect this to work for a while :)

**Comment by jmcphers** [comment]
Yes, that should do it, but I'd recommend using `xenial` or `bionic` instead of `trusty` if your base image allows.

Have you considered using a redirect link instead? Then you won't have to pull or parse `current.ver`. Try this one:

https://www.rstudio.org/download/latest/stable/server/ubuntu64/rstudio-server-latest-amd64.deb

**Comment by cboettig** [comment]
Thanks @jmcphers !  Is there an equivalent `latest` link that maps to `debian9`, to match our base image? 

(I think our parsing of `current.ver` pre-dates having `latest` links, though it's better than what approach we did before we had a `current.ver`...  using the `latest` link directly would be even better. )

**Comment by jmcphers** [comment]
There sure is.

https://www.rstudio.org/download/latest/stable/server/debian9_64/rstudio-server-latest-amd64.deb

**Comment by cboettig** [comment]
@daroczig Thanks for the help on this one.  Would you like to send a PR to update the latest/3.5.3 Dockerfile to use the `latest` link if `RSTUDIO_VERSION` is not defined and otherwise use https://download1.rstudio.org/desktop/debian9/x86_64/rstudio-${RSTUDIO_VERSION}-amd64.deb if it is defined?  

Otherwise I can probably get to it this evening or so.

**Comment by daroczig** [comment]
@cboettig, sure, I'll do that today.

Please note that this new version of RStudio Server has a new dependency it seems: `libclang-dev` -- that brings in quite a few extra as well: 

```
apt-get install -y --no-install-recommends \
    ...
    libclang-dev libclang-6.0-dev libclang1-6.0 libclang-common-6.0-dev libobjc-7-dev \
    lib32gcc1 lib32stdc++6 libc6-i386 libllvm6.0 libobjc4 libgc1c2
```
