### ISSUE TITLE
ERROR: R:   X11 is not available, I am using R 3.5.3.

### ISSUE THREAD

**Issue by avenger2129** [rocker-org/rocker-versioned#136]
When I run capabilities() in R, it fails to detect png, jpeg, tiff and x11. It's troubling me to render plots to all those formats (jpeg, png, tiff). Could somebody help me out here.

```r 
>capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
      FALSE       FALSE       FALSE       FALSE       FALSE       FALSE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS     profmem       cairo         ICU long.double     libcurl
       TRUE       FALSE       FALSE       FALSE        TRUE        TRUE
```

**Comment by eddelbuettel** [comment]
All those require X11 to determine font metrics.

**Comment by avenger2129** [comment]
Thanks for the quick response @eddelbuettel. In my case, I'm sure the R is compiled with -X configuration, yet i'm seeing it as false. is there a way to enable it it or do I have to recompile R from the scratch?

**Comment by eddelbuettel** [comment]
No, sorry, you misunderstood / I seem to have explained myself poorly:  The R version is fine.  

You would fail with any other app requiring an x11 token _the exact same way_.  When you run docker you run 'headless' (unless you go the extra mile to share your outer x11 settings).  

So if you want graphs, just use the Cairo device.

**Comment by cboettig** [comment]
@avenger2129 also see https://github.com/rocker-org/rocker-versioned/tree/master/X11 for a bit more detail.

**Comment by eddelbuettel** [comment]
And just for completeness:  some Rocker containers use a pre-built R binary, that one will always have x11 in there.  The page mentioned by @cboettig is both more specific, and more general :)  We should add the script invocation more prominently on the top or in the wiki...

**Comment by dgkf** [comment]
Just in case anyone stumbles upon this issue in the future, I want to plug a small project I took on to fill this gap. I've found using `rocker` images to containerize development environments to be super convenient - especially for jumping between different R releases and easily installing development builds for testing. The plotting has always been a pain-point, though.

I did a small weekend project ([`webviewer`](https://github.com/dgkf/webviewer)) to build an RStudio-style "Viewer Pane" that I can host from within a `rocker` container, which displays plots in a browser (as well as knitted html files, shiny apps & plotly plots). It's still a bit rough around the edges, but hopefully it's enough to start chipping away at this challenge so that plot viewing doesn't require extensive X11 setup.

**Comment by eitsupi** [comment]
@dgkf Hi, thank you for your works.

There is a package called `httpgd` that displays plots via a browser, and it works well on rocker containers. (https://github.com/nx10/httpgd/issues/66)
It may be able to meet your needs for plot display.

**Comment by dgkf** [comment]
Thanks @eitsupi - an even better option! This is awesome. I'm glad to see that I wasn't crazy thinking that this would be a useful part of the ecosystem, and equally thrilled that I got the excitement of getting to toy around in unfamiliar territory without having to maintain it :smile:

I'll refer people to this option and flag my package as superseded.

**Comment by eitsupi** [comment]
`httpgd` can also be used from Docker containers, but it was not originally designed for containers, so it would be nice if more users used it with rocker to increase its popularity.
