### ISSUE TITLE
Docker images for CRAN Task Views

### ISSUE THREAD

**Issue by ColinFay** [rocker-org/rocker-versioned#151]
Hey, 

Sorry if this is not the place where I should open this issue, but I wasn't sure where it should go so feel free to move it / point me somewhere else if you think this is not the right place :) 

I've been working on a Docker image for the Database CRAN Task View (which requires a lot of system dependencies) : https://github.com/ColinFay/r-db

I've been thinking that it's something that could be extended to more (if not all) CRAN Task Views. 

So the idea would be to have a `rocker/ctv`, with one folder by ctv, and several builds of each ctv. I've gone for the `tidyverse` in my r-db image as it makes sense with `{DBI}`, but we can go for basic `r-ver` if necessary.

Do you think this is something that can fit into rocker? If yes, I'll be happy to work on that.

Colin

**Comment by cboettig** [comment]
Good question.  Note that there's also already https://hub.docker.com/r/cran/debian, which might be a convenient base image for having all the system dependencies in place.

**Comment by cboettig** [comment]
(said image is basically a thin wrapper around a debian meta-package, `rcheckserver` which I believe Kurt maintains at `http://statmath.wu.ac.at/AASC/debian`)

**Comment by eddelbuettel** [comment]
Hm, I may have to play the role of [Debby Downer](https://www.youtube.com/watch?v=wZ1AjaNjack) here as it sounds like creeping featuritis to me.  

We don't need to package every combination of packages just because we can.  There is a *real cost* in maintaining these, and that cost is on _us_.  So at this point I am inclined to say "no thanks".  

What is easier is is simple tutorial of starting with a base rocker image, current or versioned, and showing a walk-through of how to identify and satisfy build-dependencies.

**Comment by eddelbuettel** [comment]
And @cboettig is correct about the (.deb-style) meta package Kurt is maintaining as a local effort / under the Austrian Stat Society's umbrella.

**Comment by ColinFay** [comment]
Ah yes, that makes sense. It indeed adds some maintenance cost, so supporting the whole ctv might be too much. 

+ What about the `r-db` image alone? It needs more than just sys-req — downloading impala drivers for example, or installing GEOS for RGeos.

+ Where can one contribute to tutorials for rocker? On the website?

And thanks for linking to the cran docker image, wasn't aware of that one :)

**Comment by cboettig** [comment]
@ColinFay Yeah, my thinking was along the lines of Dirk's -- basically, I think Kurt's meta-package provides a convenient solution for building a large image with sys reqs for anything on CRAN, so I think it gives a reasonable way to sidestep the need to have a rocker image for that (e.g. for testing all the CRAN taskview stuff).  

For databases, I've tried to include most of the standard stuff (DBI and friends) in `rocker/tidyverse`, since they mostly play nicely with dplyr.  I'd be happy for feedback on how we can tweak that to cover missing things!  

For geospatial, I think the CRAN images should pick up most of that too, though note you can get explicit versions of upstream GDAL, Proj, and GEOS on the devel images (https://github.com/rocker-org/geospatial/blob/devel/Dockerfile)  

Again, the goal being as Dirk says, we just don't want to expand the universe of things we are committed to maintaining, so easier if we can address these objectives without expanding the stack or point to good alternatives.  As you've both pointed out, good documentation for this would certainly help!

On that note, yeah I think the website is the most useful place, but really documentation discovery feels like a nut we haven't quite cracked.  We have a wiki on the rocker-org/rocker, but GitHub wikis seem out of fashion and many people don't find that.  There are quite a few good tutorials users have written on personal blogs scattered over the web (e.g. https://ropenscilabs.github.io/r-docker-tutorial/), though those are hard to aggregate and can become dated.  Feedback on what you feel would be the best place (or how to make rocker-project.org easier to find tutorial content?) would be super!  Also knowing what to document -- in practice our issues threads remain the best/only place lots of little things are documented, which isn't ideal but better than nothing I suppose.
