### ISSUE TITLE
Permissions issue in rocker/r-ver:devel to install packages as the `rstudio` user

### ISSUE THREAD

**Issue by nturaga** [rocker-org/rocker-versioned#177]
## Permissions issue between rocker/r-ver:devel and rocker/r-ver:3.6.1

**`drwxr-sr-x  7 root staff `** in rocker/r-ver:3.6.1 

**`drwxr-xr-x  7 root root`** in rocker/r-ver:devel 

These permissions are shown in two locations, the `/usr/local/lib/R/site-library` and `/usr/local/lib/R/library`. 

This creates an interesting problem. The directory in the `site-library` sometimes doesn't get access to be writeable while using the `rocker/rstudio` image which inherits from the `rocker/r-ver` images. This happens only when using the `rstudio` user, and it seems that that user has not been given access to write. I've checked the Dockerfile, and see that it's in the group `staff`, and think it should work as expected, but it doesn't seem to be. (https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/devel/Dockerfile#L113) 

At Bioconductor, we use the `rstudio` images to further install some packages and noticed this issue. 

To be clear, the image `r-ver:3.6.1` works well and as expected. It's the `r-ver:devel` image which has the issue. I'm presenting a comparison of the permissions in the two images.

### rocker/r-ver:3.6.1

```
root@fc182e0e34ab:/usr/local/lib/R/library# ls -al
total 128
drwxr-sr-x 32 root staff 4096 Nov 22 02:29 .
drwxr-sr-x 11 root staff 4096 Nov 22 02:29 ..
drwxr-sr-x  7 root staff 4096 Nov 22 02:29 base
drwxr-sr-x  8 root staff 4096 Nov 22 02:29 boot
drwxr-sr-x  8 root staff 4096 Nov 22 02:29 class
drwxr-sr-x  9 root staff 4096 Nov 22 02:29 cluster
drwxr-sr-x  6 root staff 4096 Nov 22 02:29 codetools
drwxr-sr-x  6 root staff 4096 Nov 22 02:29 compiler
drwxr-sr-x  6 root staff 4096 Nov 22 02:29 datasets
....
```

```
root@fc182e0e34ab:/usr/local/lib/R/site-library# ls -al
total 16
drwxrwsr-x  4 root staff 4096 Nov 22 02:29 .
drwxr-sr-x 11 root staff 4096 Nov 22 02:29 ..
drwxrwxr-x  8 root staff 4096 Nov 22 02:29 docopt
drwxrwxr-x 12 root staff 4096 Nov 22 02:29 littler
```

### rocker/r-ver:devel

```
root@a16ed58e7076:/usr/local/lib/R/library# ls -al
total 128
drwxr-xr-x 32 root root 4096 Nov 20 02:30 .
drwxr-xr-x 11 root root 4096 Nov 20 02:30 ..
drwxr-xr-x  7 root root 4096 Nov 20 02:30 base
drwxr-xr-x  8 root root 4096 Nov 20 02:30 boot
drwxr-xr-x  8 root root 4096 Nov 20 02:30 class
drwxr-xr-x  9 root root 4096 Nov 20 02:30 cluster
drwxr-xr-x  6 root root 4096 Nov 20 02:30 codetools
drwxr-xr-x  6 root root 4096 Nov 20 02:30 compiler
drwxr-xr-x  6 root root 4096 Nov 20 02:30 datasets
...
```

```
root@a16ed58e7076:/usr/local/lib/R/site-library# ls -al
total 16
drwxrwxr-x  4 root staff 4096 Nov 20 02:30 .
drwxr-xr-x 11 root root  4096 Nov 20 02:30 ..
drwxrwxr-x  8 root root  4096 Nov 20 02:30 docopt
drwxrwxr-x 12 root root  4096 Nov 20 02:30 littler
```

Please let me know if I can expand more on this issue. @mtmorgan can probably help with more information as well if it is needed.

**Comment by riccardoporreca** [comment]
@nturaga, @cboettig, I had a quick look at this, and this seems related to a different behavior with the `debian:buster`image `rocker/r-ver:devel` is based on. I could reproduce the same "wrong" permissions with `rocker/r-ver:3.6.1` (`latest`) after rebuilding the image locally based on `debian:buster` instead of `debian:stretch`.

Focusing on `site-library`, which is what should really matter, a closer look at the permissions reveals something interesting
``` bash
docker run --rm rocker/r-ver:3.6.1 bash -c 'ls -la /usr/local/lib/R | grep site-library'
## drwxrwsr-x  4 root staff  4096 Nov 24 22:33 site-library
```
``` bash
docker run --rm rocker/r-ver:devel bash -c 'ls -la /usr/local/lib/R | grep site-library'
## drwxrwxr-x  4 root staff  4096 Nov 24 22:36 site-library
```
With `rocker/r-ver:devel`, the `site-library` directory does not have the [setgid](https://en.wikipedia.org/wiki/setgid) permission `s`, which is correctly set in `rocker/r-ver:3.6.1` to allow all of its content to inherit the same same group when created.

To give the full picture of what happens when packages are installed as `root` when building the Docker image or by e.g. `rstudio`, here is full example for `rocker/r-ver:devel`:

``` bash
# create the container and keep it running
docker run -d --name test-r-ver rocker/r-ver:devel bash -c 'tail -f /var/log/dpkg.log'
# add user and install a package
docker exec test-r-ver bash -c '\
  useradd rstudio \
  && echo "rstudio:rstudio" | chpasswd \
    && mkdir /home/rstudio \
    && chown rstudio:rstudio /home/rstudio \
    && addgroup rstudio staff'
docker exec --user rstudio test-r-ver Rscript -e 'install.packages("tinytex")'
# check permissions 
docker exec test-r-ver bash -c 'ls -la /usr/local/lib/R/site-library'
# cleanup
docker rm $(docker stop test-r-ver)
## 891d9b2186e1b0c64e5389e64f723cb9859ef7aafd9f738ab6b8e0162952f5aa
## Adding user `rstudio' to group `staff' ...
## Adding user rstudio to group staff
## Done.
## Installing package into ‘/usr/local/lib/R/site-library’
## [...]
## * installing *source* package ‘xfun’ ...
## [...]
## * installing *source* package ‘tinytex’ ...
## [...]
## drwxrwxr-x  1 root    staff   4096 Nov 25 00:05 .
## drwxr-xr-x  1 root    root    4096 Nov 24 22:36 ..
## drwxrwxr-x  8 root    root    4096 Nov 24 22:36 docopt
## drwxrwxr-x 12 root    root    4096 Nov 24 22:36 littler
## drwxrwxr-x  6 rstudio rstudio 4096 Nov 25 00:05 tinytex
## drwxrwxr-x  7 rstudio rstudio 4096 Nov 25 00:05 xfun
## test-r-ver
```

When running the same in `rocker/r-ver:3.6.1`, all directories retain the `staff` user instead.

**Comment by riccardoporreca** [comment]
The behavior described above seems to indeed go back to a difference in the permissions for the top-level `/usr/local` in `debian:buster` vs. `debian:stretch`
``` bash
docker run --rm rocker/r-ver:3.6.1 bash -c 'ls -la /usr'
## total 40
## drwxr-xr-x 1 root root  4096 Nov 18 00:00 .
## drwxr-xr-x 1 root root  4096 Nov 25 00:17 ..
## drwxr-xr-x 1 root root  4096 Nov 24 22:34 bin
## drwxr-xr-x 2 root root  4096 Sep  8 10:51 games
## drwxr-xr-x 1 root root  4096 Nov 24 22:34 include
## drwxr-xr-x 1 root root  4096 Nov 24 22:34 lib
## drwxrwsr-x 1 root staff 4096 Nov 18 00:00 local
## drwxr-xr-x 1 root root  4096 Nov 24 22:34 sbin
## drwxr-xr-x 1 root root  4096 Nov 24 22:34 share
## drwxr-xr-x 2 root root  4096 Sep  8 10:51 src
```

``` bash
docker run --rm rocker/r-ver:devel bash -c 'ls -la /usr'
## total 40
## drwxr-xr-x 1 root root 4096 Nov 18 00:00 .
## drwxr-xr-x 1 root root 4096 Nov 25 00:17 ..
## drwxr-xr-x 1 root root 4096 Nov 24 22:37 bin
## drwxr-xr-x 1 root root 4096 Nov 24 22:36 games
## drwxr-xr-x 1 root root 4096 Nov 24 22:37 include
## drwxr-xr-x 1 root root 4096 Nov 24 22:37 lib
## drwxr-xr-x 1 root root 4096 Nov 18 00:00 local
## drwxr-xr-x 1 root root 4096 Nov 24 22:37 sbin
## drwxr-xr-x 1 root root 4096 Nov 24 22:37 share
## drwxr-xr-x 2 root root 4096 Nov 10 12:17 src
```

Not sure whether this is an intentional feature appearing upstream in `debian:buster`, in case one could fix it just for `/usr/local/lib/R/site-library` by using `chmod g+ws` instead of
https://github.com/rocker-org/rocker-versioned/blob/a796a52f6d08f74891decf28b1c5c5b99d66b237/r-ver/devel/Dockerfile#L114

**Comment by cboettig** [comment]
@nturaga Thanks for the detailed bug report and thanks @riccardoporreca for the detailed splunking here.  A pull request with the `chmod` patch would be most welcome!

 Not sure if @eddelbuettel has any insight as to why default permissions for `/usr/local` would have changed between `stretch` and `buster`?

**Comment by eddelbuettel** [comment]
Yes, I was about to pipe in but then ... I didn't quite know what to add.  There _may_ have been a distro-wide change between `stretch` and `buster` but I don't recall any more.  I am however pretty sure that the setup in the standardard .deb packages for R (_i.e._ package `r-base-core` and friends) has not changed in a while.  It still does this in the `postinst` script:

```r
    # edd 03 Apr 2003  cf Section 10.1.2 of Debian Policy
    if [ ! -e /usr/local/lib/R ]; then
      if mkdir /usr/local/lib/R 2>/dev/null; then
	chown root:staff /usr/local/lib/R
	chmod 2775 /usr/local/lib/R
      fi
    fi
    if [ ! -e /usr/local/lib/R/site-library ]; then
      if mkdir /usr/local/lib/R/site-library 2>/dev/null; then
	chown root:staff /usr/local/lib/R/site-library
	chmod 2775 /usr/local/lib/R/site-library
      fi
    fi
```

And note the date ...  Hasn't changed in some time.  Current source is https://salsa.debian.org/edd/r-base/blob/master/debian/r-base-core.postinst#L42 and lines below it.

**Comment by riccardoporreca** [comment]
Thanks @eddelbuettel for the additional insights.

Indeed, after years-long discussions (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=299007, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=484841), this was changed in `buster` with the removal of `/etc/staff-group-for-usr-local`, see https://launchpad.net/debian/buster/+source/base-files/+changelog 
```
  * Do not create /etc/staff-group-for-usr-local on new installs anymore.
```
and the current debian policy https://www.debian.org/doc/debian-policy/ch-opersys.html#site-specific-programs.

Not being a Debian (policy) expert, I am wondering if making `/usr/local/lib/R/site-library` `2775` again via `chmod g+ws` in
https://github.com/rocker-org/rocker-versioned/blob/a796a52f6d08f74891decf28b1c5c5b99d66b237/r-ver/devel/Dockerfile#L114
is considered legitimate. I assume so since, as mentioned, this is what `r-base-core` .deb _et al._  do, which I am e.g. using on my local Ubuntu 18.04 installation, where `/etc/staff-group-for-usr-local` was also removed.

@eddelbuettel any input about whether we can and should indeed go for `chmod g+ws`?
I will be happy to contribute a PR with the patch, also considering whether we need something similar for TinyTeX in `rocker/verse`
https://github.com/rocker-org/rocker-versioned/blob/a796a52f6d08f74891decf28b1c5c5b99d66b237/verse/Dockerfile#L73-L76

@cboettig, besides `devel`, I assume this patch should also be already included in the `latest` image to be `buster`-ready.

**Comment by eddelbuettel** [comment]
Well there are Debian _distro-wide_ policies, and then there is what I do just in _my package_. I referred to the latter, and that was just below `/usr/local` affecting only the `site-library` directory for R.  And still seems to work in Debian as I have no open bug reports or complaints there.

Rocker is not a Debian project so no worries about policies compliance relative to Debian there.  I think you are close and I think can leave this up to @cboettig and you to sort out for the r-ver stack.

**Comment by eddelbuettel** [comment]
That said, I really appreciate your digging and it is likely that the policy change you documented had some effects.  But I think we don't need to go overboard disentangling: we have to set a decent working group-write setting, and the make sure our default user is in that group.

(And even then there will be unhappy folks as we also get bug reports where people want nothing but per-user installations.  Preferences continue to differ ...)

**Comment by riccardoporreca** [comment]
@cboettig, see PR #179, which includes details especially about testing the changes based on updated images built locally, and also covers a minor refinement of `rocker/verse`.

**Comment by nturaga** [comment]
Thanks a lot!
