### ISSUE TITLE
Proxied authentication

### ISSUE THREAD

**Issue by bruth** [rocker-org/rocker-versioned#182]
I apologize for posting here since its not technically applicable to the Docker image itself, but I could not find whether the non-Pro version of RStudio supports proxied authentication. I read about this on the RStudio Connect docs that seem to use and trust the `x-auth-username` header if set in the request. Does this also apply to this version of RStudio? Thank you!

**Comment by cboettig** [comment]
Hi @bruth , thanks for the question.  With a bit of know-how, you can run just about any web service behind a reverse proxy server (think Apache, Nginx, Caddy), including the open source RStudio Server.  Most of those have the option of providing an authentication step before connecting you through to a service (and can be useful for other things, like serving your service on https, the 443 port instead of over the 8787 port).  

It sounds like you're referring to https://docs.rstudio.com/connect/1.6.8/admin/authentication.html#authentication-proxy, which is in the documentation for RStudio Connect, which as you know is a different product and part of the commercial/enterprise offerings.  I'm not an expert in this area, but from my read of that section it sounds like this is saying basically the same thing -- you can put Connect behind your own proxy server, and it'll just pass on the headers but you're on your own for secure authentication if you're going this way.  

Not sure if any of that was helpful.  Maybe if you can share a bit more about what you are trying to accomplish?

**Comment by bruth** [comment]
@cboettig I appreciate the response. The setup I want to achieve is a multi-user RStudio instance where the session user is defined by the proxy. I am currently initializing the RStudio container with auth enabled, but I extended the container to create a set of Linux users which will share the instance. These users are predetermined and will be authenticated through an external means. Given this setup I want to map the authenticated username to the local RStudio (Linux) user. This is what the proxied authentication offers.. essentially RStudio is trusting the upstream proxy to provide the username of the local user the session pertains to.

**Comment by cboettig** [comment]
@bruth cool, yup, I follow you now, but I don't think the opensource RStudio Server will read the header, though I'm not 100% sure. I suppose one can have the user sign in twice, once to the proxy, once at the RStudio login, though clearly that's not ideal.  Not sure if you can have the proxy use the pam authentication route, but that's what we do to facilitate the multi-user sessions for singularity users (see https://www.rocker-project.org/use/singularity/)

I don't suppose you'd want to go the route of happing separate docker containers running separate instances of the rstudio server for each user?  It's still possible to use shared volumes on those images to share a system library, etc.

**Comment by bruth** [comment]
Thanks @cboettig.

> I don't suppose you'd want to go the route of happing separate docker containers running separate instances of the rstudio server for each user?

Yes, this was an idea I had in the past, but wanted to see if a multi-tenant setup could work. However for my particular use case, which includes hosting compute environments with a few different frontends (user choice of R Studio, Jupyter, etc.) I am realizing that multi-tenancy has been hard for all of these. So a one container-per-user with a routing layer is much more attractive now.

I appreciate the help!
