### ISSUE TITLE
rocker/r-ver:devel needs to be rebuilt

### ISSUE THREAD

**Issue by nturaga** [rocker-org/rocker-versioned#197]
Hi @cboettig 

Can you issue a rebuild of rocker/r-ver:devel on dockerhub, so that it captures the latest revision of r-devel (r78000) ?

When I try to build locally, I get the error

```
checking whether PCRE support suffices... no
configure: error: PCRE2 library and headers are required, or use --with-pcre1 and PCRE >= 8.32 with UTF-8 support
/bin/sh: 1: Rscript: not found
```

The latest r-devel contains some significant changes such as `stringsAsFactors = FALSE` needs to be changed to `stringsAsFactors=TRUE`.

Best regards,

Nitesh

**Comment by eddelbuettel** [comment]
[ I know you asked for r-ver but if you want r-devel I have the rocker/r-devel and rocker/drd images on a weekly cronjob -- fresh every Sunday. Ditto for r-patched in rocker/drp. ]

**Comment by nturaga** [comment]
Thanks @eddelbuettel , I guess my end goal is to be able to use the latest r-devel from rocker/rstudio:devel. And since rocker/rstudio:devel depends on rocker/r-ver:devel, i thought this needed to go through.

**Comment by eddelbuettel** [comment]
Turns out it is (likely) the pre-release stage of R itself.  I just pulled a refreshed `drd`, and had checked it built on the weekend yet

```sh
edd@rob:~$ docker run --rm -ti rocker/drd RD --version
R Under development (unstable) (2020-03-07 r77914) -- "Unsuffered Consequences"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

edd@rob:~$ 
```

We had that once before leading up to a new R release but I have too many other balls in the air now to deal with this.   You may have to build locally if you need an immediate fix as I would surmise that the r-devel images is affected  similarly.

**Comment by eddelbuettel** [comment]
Found the issue reported three days ago -- caching is too blame:

```
edd@rob:~$ docker run --rm -ti rocker/r-devel RD --version | head -1
R Under development (unstable) (2020-03-22 r78027) -- "Unsuffered Consequences"
edd@rob:~$ docker run --rm -ti rocker/drd RD --version | head -1
R Under development (unstable) (2020-03-21 r78023) -- "Unsuffered Consequences"
edd@rob:~$ 
```

The (rather large) `rocker/r-devel` and the (more compact) `rocker/drd` are both up-to-date.  One uses SVN, the other downloads a tarball hence the slight difference in commits.  Both rebuilt this morning and settings changed so that the weekly builds should again produce fresh weekly images.

**Comment by cboettig** [comment]
build has been tickled.  (r-ver has too many tags now and hub seems to be struggling with the cron triggers, hope to have this fixed probably in time for the 4.0.0 release)

**Comment by nturaga** [comment]
@cboettig Can you tickle the rocker/rstudio:devel build as well please? :D

**Comment by cboettig** [comment]
queued!
