### ISSUE TITLE
rocker/tidyveser, rocker/verse is not loaded in the browser 

### ISSUE THREAD

**Issue by anarinsk** [rocker-org/rocker-versioned#231]
Today, I tried to connect rocker images with `localhost:8787.` But there is no response. 
After around two minutes of loading screen, I saw the below message

![image](https://user-images.githubusercontent.com/3413866/88016935-8613d600-cb5f-11ea-8417-04fba4c8b8a3.png)

Working Environment 

1. Windows 10 Build 20170.rs 
2. Ubuntu 20.04 in WSL 2 
3. Chrome lastest version

**Comment by cboettig** [comment]
Are you loading a fresh container or connecting to a currently active environment?  Are you mapping to a local volume?  Have you tried waiting a bit longer?  Have you tried any of the button/options listed in the message?  If so, what happened? Have you previously had success with the rstudio-based containers on your current machine, or is this the first time trying it?  Have you tried any of the older tags, e.g. rocker/rstudio:3.6.3 instead?

If you are trying to connect to a previously active session which had relatively large objects loaded into the namespace you will see this, since R will take a while to re-load them from cache.  

Which docker version are you using?  Are you running docker within the WSL, or the native windows docker?  (strongly recommend the latter, and preferably with docker CE and not docker toolbox, though you need Windows edu or pro addition I think to run community edition).

**Comment by stubclan** [comment]
A little more information here would certainly be helpful in helping you @anarinsk

**Comment by anarinsk** [comment]
I'm so sorry not to describe the situation enough. Today, I checked rocker image after updating docker desktop from 2.3.3.1 to 2.3.3.2. The problem was solved. Thanks for following the issue.
