### ISSUE TITLE
Missing dependencies for tutorials

### ISSUE THREAD

**Issue by ITmaze** [rocker-org/rocker-versioned#237]
In (re)acquainting myself with R-studio I've pulled the :latest tagged image and am using the in-build tutorial. Compliments to the developers of the tutorials.

One thing that I'm finding is that the image as supplied doesn't have all the dependencies for running the tutorials. I understand why you might not want those in the base image, but it seems trivial to create a tagged version that has the dependencies needed for the tutorials.

I've also identified two Debian packages that also prevent the tutorials from running.

Here's what I've found missing in R-studio so far:
* learnr
* rstudioapi
* nycflights13
* tidyverse
* Lahman
* sortable
* dygraphs

Here's what I've found missing in the underlying Debian installation:
* libxt6
* libxml2

**Comment by cboettig** [comment]
Thanks.  Please note that we already provide other images such as `rocker/tidyverse` and `rocker/verse` that have most of these packages installed.  `tidyverse` in particular pulls in over 80 different packages and dramatically increases the image size, which is why we don't ship it in `rocker/rstudio`.   Apologies if this is confusing, perhaps we can do a better job of pointing people to these more 'batteries-included' images.  

That said, maybe we should move `libxml2` (currently added at `rocker/tidyverse` and maybe also `libxt6` (currently not added until `rocker/verse`) up to be part of `rocker/rstudio`, since they are quite small.  Then a user could benefit from RSPM installs of the R packages while being able to start with the slimmer base image.

**Comment by ITmaze** [comment]
Perhaps we're talking cross-purpose here.

I was envisaging a "tutorial" tagged image that had the minimum image that would run the tutorials using the rocker/rstudio image, so instead of pulling rocker/rstudio:latest, you'd pull rocker/rstudio:tutorial and you'd have enough to do the tutorials.

I realise that I also combined some missing Debian dependencies. I'm not (yet) familiar enough with the rocker/rstudio image to determine if these two packages are only needed for the tutorials, or if their absence would have caused issues at a future point.

**Comment by cboettig** [comment]
@ITmaze Thanks for clarifying.  We'd rather not create new tags for each specific use case though.  Having too many tags makes it hard for users to figure out which image they need and increases the maintenance surface.  I strongly recommend that users wanting tutorials to work out of the box, (or other common features to work out of the box like rmarkdown::render to pdf, etc) to start with the `rocker/verse` base image.
