### ISSUE TITLE
installGithub.r fails with error

### ISSUE THREAD

**Issue by MatthiasHinz** [rocker-org/rocker-versioned#26]
Hi,
I noticed that for the latest build of `rocker/r-ver` executing the littler installation script `installGithub.r` fails with the following error: 

`Error in library(remotes) : there is no package called ‘remotes’

Since the latest littler-release, the script [attempts to load the package 'remotes'](https://github.com/eddelbuettel/littler/blob/master/inst/examples/installGithub.r#L11), but the package is not installed.

Could be fixed by including `remotes` in the rocker images. 
Probably, the installation script could also be patched by replacing the function 'library()' with 'require'. 'library()' fails with an error if the library is not available.

**Comment by cboettig** [comment]
As you see, the script is part of the `littler` R package, and so maybe file an issue in that repo regarding `library()` vs `require()`.  The rocker stack picks up `remotes` at `rocker/tidyverse`, so it's not available in `r-ver`.  We could consider moving it up the stack, but I've tried to keep `r-ver` down to base-r and littler-required packages.  (It's nice to have `install2.r in r-ver so that base R packages can be installed in Dockerfiles without the verbose `Rscript -e` calls, but installGithub.r feels like a more specialized case, particularly since it's at odds with the versioning provided by using CRAN-like repos of install2.r).

**Comment by eddelbuettel** [comment]
It's similar with littler.  The installGithub.r script is one of many examples, we do not depend on everything the examples need.   And with the move from the (arguably overarching) devtools down to smaller micropackages I switched to remotes.  But it needs to be present.

**Comment by MatthiasHinz** [comment]
I understand. So, I will make adjustments in my implementation where rocker images are in use. Thanks for the information!
