### ISSUE TITLE
consider tini as alternative to s6?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker-versioned#33]
As recommended in the official images guidelines: https://github.com/docker-library/official-images#init

**Comment by mbeigel** [comment]
Interesting. Since Tini only spawns a single child according to: https://github.com/krallin/tini, how do intend to deal with the option to run Shiny Server? Would Tini run a shell script that in turn runs RStudio Server and Shiny Server, or could/should Shiny Server be removed from the RStudio containers?

**Comment by cboettig** [comment]
Thanks, @mbeigel , your research on this is ahead of mine.  An init service that only runs one task seems a bit silly.  We also have downstream users who have added other services to s6 (ssh and the like), so changing at this point seems unwise.  I've been very happy with s6 myself (after being frustrated with supervisord and runit), I think it's a very well thought out, light but fully featured init system.   So I'm glad the `tini` limitation gives us good cause to close this!
