### ISSUE TITLE
Deprecated packages in tidyverse:latest

### ISSUE THREAD

**Issue by adrtod** [rocker-org/rocker-versioned#35]
For instance the version of dplyr installed is 0.5.0 while the version on cran is 0.7.0.
Apparently, that comes from the installation of bioconductor in the Dockerfile.
```
 && R -e "source('https://bioconductor.org/biocLite.R')" \
```
Why is bioconductor needed anaway?

**Comment by eddelbuettel** [comment]
Are you sure it is not just due to not having been rebuilt in the fewer than seven days since dplyr 0.7.0 was released?

**Comment by adrtod** [comment]
Yes that's right ;)
Version 0.6.0 was out on may but never published on CRAN, hence my confusion.
I just have to use the devel then!

**Comment by cboettig** [comment]
@adrtod quick postscript: 

re bioconductor: The `tidyverse` image includes all suggested as well as required dependencies of `tidyverse` and `devtools`.  Since the latter suggests a bioconductor package we need those repos.  There are of course no MRAN snapshots for bioconductor, since it already uses versioned releases based on the R version you're running.  Like Dirk says this has nothing to do with `dplyr` ;-)

re rebuild dates: That's actually a good idea -- as you've noticed `devel` version is built nightly, but the other versions are only re-built once a month (they are mostly stable anyway so rebuilding is just a way to pick up security patches to old debian sources).  But we can probably add `latest` to the nightly builds without issue.  

re versions: no need to switch to `devel` just to get the latest `dplyr`; `latest` uses the RStudio CRAN mirror, not an MRAN mirror, so `update.packages()` or `install.packages()` on `latest` will set you right.

re dpylr 0.6.0: correct, in the new versioning scheme odd-numbered releases signify breaking changes, see https://blog.rstudio.org/2017/06/13/dplyr-0-7-0/.  (Why the odd-number rule instead of http://semver.org/ I have no idea).

**Comment by adrtod** [comment]
@cboettig things are very clear now, thanks!
