### ISSUE TITLE
Reported image size does not match docker output

### ISSUE THREAD

**Issue by jgbradley1** [rocker-org/rocker-versioned#45]
This may be a misunderstanding on my part but when I run

`docker pull rocker/rstudio:latest`

the downloaded image is 1.06 GB instead of the expected 328.4 MB. Am I using the wrong image or what could be taking up so much space in the rstudio image? I was hoping to find a rstudio image that has just the standard R installation (with Rstudio) included in order to keep the image size small.

**Comment by cboettig** [comment]
The image sizes reported by Docker Hub and our badges refer to the size of the *compressed* download, (since users are usually more concerned about download size/times than disk space).  

The `rocker/rstudio` image is a 344 MB download, though it's actually smaller still (113 MB) if you have already downloaded the previous image layers, `debian:stretch` (45 MB) and `rocker/r-ver` (185 MB), as you can see in this screenshot:

![image](https://user-images.githubusercontent.com/222586/29491794-679564a6-851b-11e7-8705-72803a43c5e6.png)

(The last two layers you see listed there are the docker COPy and default CMD layers that don't add more space)

The unpacked image size (e.g .as shown by `docker images`) is indeed about 1 GB.  You should be able to see exactly what is on the images by looking at the Dockerfiles, it really is just a Debian base, a basic (though not absolutely minimal; e.g. has support to compile packages with source code etc) R instance plus RStudio and little else.  

Hope this helps.
