### ISSUE TITLE
rocker/geospatial:3.4.0 images on dockerhub has rstudio v 1.0.x (?)

### ISSUE THREAD

**Issue by dlebauer** [rocker-org/rocker-versioned#54]
I am using rocker/geospatial:3.4.0. Howver, from https://github.com/rocker-org/rocker-versioned#images and comments in https://github.com/rocker-org/rocker-versioned/issues/53 it looks like this should pull from rocker/rstudio:latest, which I expect would have rstudio 1.1.383 . However the latest build of rocker/geospatial:3.4.0 (pulled 30 min ago) still has 1.0.x. 

Assuming that I am correct and geospatial:3.4.0 should have rstudio v. 1.1.x, 

Is it possible that DockerHub rebuilt this stack of images in the 'wrong' order so that the updated rstudio:latest did not propagate to geospatial:3.4.0 and similar downstream / dependent images? Or is there another reason that these still have the old rstudio?
 
Would it fix the issue if you rebuilt this stack (and if so, could you please do so)?

Otherwise, I can add the commands for installing rstudio to my downstream dockerfile (https://github.com/terraref/toolserver-dockerfiles/pull/8) but would prefer not to.

**Comment by cboettig** [comment]
Thanks for filing this issue.  Yeah, the tagged images are only rebuilt once a month by default.  Sometimes the docker hub build will fail randomly; e.g. if `rocker/tidyverse:3.4.0` failed to build last month, say, then downstream `3.4.0` images are inheriting a 2-month old `tidyverse` and hence old `rstudio`.  You should be able to see all the build dates on hub; e.g. for tidyverse: 
https://hub.docker.com/r/rocker/tidyverse/builds/ .  (Had a lot of builds failing randomly on Hub a few weeks ago that is probably responsible, Hub seems to have gotten a bit better now but not perfect, as evidenced by Error builds in the logs which are almost always Hub's fault!)

So rebuilding `geospatial:3.4.0` might be all it takes if `verse:3.4.0` is up-to-date, otherwise check `tidyverse:3.4.0`, maybe most of that tag stack is behind.  I'll queue some rebuilds and maybe check tomorrow if things have fixed?

Related to this, arguably the tagged stacks should not be pulling `rstudio:latest` all the time, but should be version-stable with relation to the RStudio tag as they are in relation to almost all the other software involved.  Mostly I just haven't gone through the RStudio release dates to collate them with the R release dates.  Thoughts on this?

**Comment by cboettig** [comment]
ah right, RStudio 1.1 was released Oct 9th, so hasn't hit any of the tagged images yet (cron rebuilds them on the first of the month to decrease load on hub; since other than rstudio releases they shouldn't change!).

anyway, I've queued the 3.4.0 stack; so unless a build fails, RStudio 1.1.x should propagate through `geospatial` by tonight.

**Comment by dlebauer** [comment]
Hi Carl - thanks for rebuilding these. I did check the /tags endpoint of a few of the docker containers (e.g. https://hub.docker.com/r/rocker/verse/tags/) to see the latest builds, and it appeared in many cases (e.g. verse:3.4.0) that the versioned images had been rebuilt 14 days ago, (approx. Oct 9). So I assumed that had been an intentional attempt to get the latest rstudio version.

With respect to using rstudio:latest in versioned builds. I am a fan of using rstudio:latest since Rstudio keeps coming out with great new features that quickly become 'must haves'. If there were a common case where using a version of rstudio were important for reproducibility's sake I might reconsider, but most cases I can think of are either rare or not good practice for reproducibility (e.g. relying on GUI interaction that could be scripted, especially since Rstudio does a good job of converting button pushes into commands). 

I'll close the issue and reopen if rebuilding doesn't solve the problem.

**Comment by cboettig** [comment]
Cool, we'll keep RStudio tagged at latest.  like you say, reproducibility should really be independent of the IDE anyway.  I agree the new features are hard to give up; I'm a huge fan of the new embedded tty terminal (can do tab completion, top, etc), the old terminal was nearly useless.  

Hub is fast today, looks like `geospatial:3.4.0` should now have the RStudio 1.1.

**Comment by dlebauer** [comment]
just confirmed that it propagated through geospatial:3.4.0. Thanks!
