### ISSUE TITLE
Container environment in RStudio

### ISSUE THREAD

**Issue by rstub** [rocker-org/rocker-versioned#74]
Currently if I set environment variables via `docker run --environment ...` these are not visible in RStudio. AFAIK one has to replace `/bin/bash` with `/usr/bin/with-contenv bash` in `/etc/services.d/rstudio/run` to change this. Anything speaking against such a change?

**Comment by cboettig** [comment]
@rstub Thanks, I believe you're correct: it would be better for us to use`/usr/bin/with-contenv bash` in https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/Dockerfile#L67, like we do in [userconf.sh](https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/userconf.sh#L1).  Would you care to send a PR for this?

**Comment by rstub** [comment]
I just tried to create a PR. However, I do not understand how changes to `rstudio/Dockerfile` are synced to `rstudio/<version>/Dockerfile`, since there is no `sync` target in `rstudio/Makefile`.

**Comment by cboettig** [comment]
Short answer is "manually."

Not all changes are backwards compatible with earlier versions; some edits need to be manually adjusted for differences between stretch and jessie, some shouldn't be backported at all, so I found it was better to drop the `sync` targets than accidentally sync incompatible changes.  

This one seems to me like the kind of bug-fix that should be backported to all earlier versions; since I believe it corresponds with the originally expected behavior anyway.  Thanks!
