### ISSUE TITLE
Environment variables for rstudio user

### ISSUE THREAD

**Issue by vnijs** [rocker-org/rocker-versioned#91]
I am trying to setup a docker container that would make it easy to use Rstudio and Python with [reticulate](https://github.com/rstudio/reticulate). I have tried numerous different approaches to get the Rstudio terminal to pick up the "PYTHONUSERBASE" environment variable and cannot seem to get it to work. I can get it to work with Jypyter Lab however, so I must be missing something about how R(studio) works in Docker and hope you can provide some suggestions. 

If I use the command below to start up Rstudio server I cannot see the environment variable at all in the Rstudio terminal ([based on SO post](https://stackoverflow.com/a/30494145/1974918))

```
docker run -e PYTHONUSERBASE='~/.rsm-msba' --rm -p 8787:8787 rocker/rstudio
```

I have also tried adding `ENV PYTHONUSERBASE=/home/rstudio/.rsm-msba` in a Dockerfile. The terminal in Jupyter Lab picks this up fine but not the Rstudio terminal, *unless* I first use `su - rstudio`. That seems odd because `whoami` already says the user is `rstudio`. See output below.

Something similar happens with the MRAN environment variable set in the rocker docker file for Rstudio:

```
rstudio@01f6f599f7f2:~$ echo $MRAN

rstudio@01f6f599f7f2:~$ su - rstudio
Password:
$ echo $MRAN
https://mran.microsoft.com/snapshot/2018-08-08
$
```

FYI The point is to get python3 to pick up this environment variable so that packages are installed and loaded from a custom directory that will not conflict with the anything in the user's home directory if they also use python on macOS or Windows

**Rstudio terminal:**

```
rstudio@2aa2a6f773a7:~$ python3 -m site
sys.path = [
    '/home/rstudio',
    '/usr/lib/python35.zip',
    '/usr/lib/python3.5',
    '/usr/lib/python3.5/plat-x86_64-linux-gnu',
    '/usr/lib/python3.5/lib-dynload',
    '/usr/local/lib/python3.5/dist-packages',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '/home/rstudio/.local' (doesn't exist)
USER_SITE: '/home/rstudio/.local/lib/python3.5/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
rstudio@2aa2a6f773a7:~$ su - rstudio
Password:
$ python3 -m site
sys.path = [
    '/home/rstudio',
    '/usr/lib/python35.zip',
    '/usr/lib/python3.5',
    '/usr/lib/python3.5/plat-x86_64-linux-gnu',
    '/usr/lib/python3.5/lib-dynload',
    '/usr/local/lib/python3.5/dist-packages',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '~/.rsm-msba' (doesn't exist)
USER_SITE: '~/.rsm-msba/lib/python3.5/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```

**Jupyter lab terminal:**

```
rstudio@feffab7977ea:~$ python3 -m site
sys.path = [
    '/home/rstudio',
    '/usr/lib/python36.zip',
    '/usr/lib/python3.6',
    '/usr/lib/python3.6/lib-dynload',
    '/usr/local/lib/python3.6/dist-packages',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '/home/rstudio/.rsm-msba' (exists)
USER_SITE: '/home/rstudio/.rsm-msba/lib/python3.6/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
rstudio@feffab7977ea:~$
```

**Comment by cboettig** [comment]
Thanks for getting in touch, bare with me a moment as I don't entirely follow your question above.  You note: 

> FYI The point is to get python3 to pick up this environment variable so that packages are installed and loaded from a custom directory that will not conflict with the anything in the user's home directory if they also use python on macOS or Windows

If you're running a Docker container without linking local volumes, as in your example call above, then the container is completely isolated from the host and there is no concern that anything will conflict with the users home directory regardless of what OS they are running.  

Similarly, there is not going to be a `~/.rsa-msba` directory in the container unless the user creates it (or a juypter-lab instance on rocker/rstudio image, unless the user installs it).  So I'm afraid I do not entirely follow the context of your comments above.

There's probably some subtlety here, but FWIW I frequently install reticulate on rocker images and haven't had any issues there.  We have a few in-development images that should provide a more fully CUDA GPU-enabled bindings which do require a bit more configuration, but I don't believe any custom env var should be needed to use reticulate, at least from the RStudio side.  Apologies if I haven't followed or have totally miss-understood your question.

**Comment by vnijs** [comment]
I do actually use `-v ~:/home/rstudio`, at least for macOS and Linux host systems. Sorry I didn't mention that. 

I think the issue I'm having might be linked to how [Rstudio sets up the terminal](https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal?version=1.2.830&mode=server#lifetime) to use `/usr/bin/env bash -l`. If that is the issue, any idea how to use a _standard_ bash configuration?

I'd like students to use `pip3 install --user somepackage` from the terminal and the package would go to ".rsm-msba`, or whatever, `PYTHONUSERBASE` is set to, that will not be used by any version of python on the host system. By having `PYTHONUSERBASE` set `import somepackage` would also be able to find such packages and not look in .local which might have packages installed from the host system.

**Comment by cboettig** [comment]
I really wouldn't recommend linking the home directory directly, *particularly* if you are installing software there instead of at the system level.  All software dependencies should really be installed in the container itself.  For teaching, it's often helpful to write a Dockerfile in advance in which the software necessary (e.g. the python libraries) gets pre-installed. (If teaching the use `pip3` is part of the point, that's another matter obviously).  

Note reticulate provides bindings to install python libraries directly from R, which can be a separate rabbit hole but is sometimes most expedient.  

Ah, so you're using the RStudio terminal and not the native bash terminal. As you saw in the RStudio docs, those run under the user env, not the root environment, hence you don't see the environment variable you set in the run command in that terminal.  Of course once in that terminal you can set whatever env vars you need still, but as I comment above, with containers I think you really do want to install libraries at the system level.  Remember it is all still in the container and no way impacts the host OS installation.  

HTH,

**Comment by vnijs** [comment]
The vast majority of R and Python packages will indeed be in the container. However, if students are doing a group project they should be able to install a few packages in a way that persists. Then there is also the part about student use of `pip3` and `install.packages` as you mention.

I'll ask on Rstudio community if there is a way to get Rstudio to use a native bash terminal. Thanks for your suggestions @cboettig and, of course, for your great work on rocker

**Comment by cboettig** [comment]
Thanks, yes, I see your point, though I do not think that installing software to a local volume is generally our recommended strategy for persistence.  Students can save and commit the container directly, or they can write a separate Dockerfile that pre-installs these additional libraries.  I think you're right that it could work in this context, but will in general be more fragile and less portable, and could have unintended side-effects on the host operating system.  

Note that of course you can put whatever environmental variables you want to put in bash, I don't think this is an RStudio issue per se.  We have chosen in the rocker image not to duplicate the root env session over to the `rstudio` use env, but you could easily modify this (e.g. setting these variables in the home dir you are already linking, or just adding the env var before running pip scripts).  Anyway, thanks for the kind words and hope this is helpful; but otherwise just ignore :)

**Comment by vnijs** [comment]
Docker is new to students and other faculty in the program this year. Ideally all packages students need are in the container, however, we need some flexility. Committing changes is a nice idea but not practical for the program right now. 

I have experimented with different way to set `PYTHONUSERBASE` so it will show up in the Rstudio terminal environment (see some attempts below). I'd like it to be set by default in the container but can't find a way to make it show up. Any suggestions? How would you "duplicate the root env session over to the rstudio use env"?

```
RUN echo "PYTHONUSERBASE=~/.rsm-msba" >> /etc/environment
RUN echo "PYTHONUSERBASE=~/.rsm-msba" >> /etc/R/Renviron
RUN echo "PYTHONUSERBASE=~/.rsm-msba" >> /etc/R/Renviron.site
```

**Comment by cboettig** [comment]
I was thinking something like `/home/rstudio/.bashrc` instead, but those might work, not sure.   We put `MRAN in `/etc/environment` so maybe not since you're not seeing that in the RStudio terminal; I'm away from a real computer at the moment.  I tend to use `/usr/local/lib/R/etc/Renviron` in r-ver, which RStudio writes over to `/etc/R/Renviron`, but not sure if the RStudio terminal respects that.

I do appreciate that you want a solution that's as simple as possible.  Why not just instruct users to omit the `--rm`, and maybe use `--restart=always` so the existing container is just usually running whenever docker is running and the changes aren't quite so transient?  My intuition is that would have fewer headaches (and having to do a few pip installs a second time if the container is removed would be ok) than mapping volumes to persist installs, but maybe not.

**Comment by vnijs** [comment]
@cboettig Based on Rstudio's [documentation](https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal?version=1.2.830&mode=server#lifetime):

"The default terminal is started with this command: /usr/bin/env bash -l
This shell process runs as a **child process of the R session process** (rsession / rsession.exe) of the current RStudio instance, and **will inherit environment variables from that process**."

This statement suggests I must have missed something in my previous attempts to get this working. The setup below adds `PYTHONUSERBASE` as a regular environment variable, which I need for Jupyter Lab, and also adds the appropriate value for the environment the Rstudio terminal has access to. Not very clean but it works as intended.

ARG PYBASE=/home/rstudio/.rsm-msba
ENV PYBASE=${PYBASE}
ENV PYTHONUSERBASE=${PYBASE}
RUN echo "PYTHONUSERBASE=${PYBASE}" >> /etc/R/Renviron.site
