### ISSUE TITLE
Size of R images

### ISSUE THREAD

**Issue by robertdj** [rocker-org/rocker-versioned#96]
Hi 

I am curious to find out why images with R are so large. Looking at `rocker/r-ver` I get a list of the installed packages in the image:

    docker run --rm rocker/r-ver:latest dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n

Here `openjdk-8-jre-headless` weighs in at almost 100 MB. However, the only Java package installed is in the `BUILDDEPS` packages that are deleted after R has been compiled. 

I am familiar with the layered concepts of Docker images and that one should minimize the data added in a single `RUN` statement. But in these versioned images there is only one big `RUN`, so I suppose that this is not the issue here?

**Comment by cboettig** [comment]
The base image, `debian:stretch`, is about 50 MB compressed; `r-ver` is about 250 MB compressed.  I believe most of that size comes from including a fully functional set of compilers.  I think you can get a smaller R image without those if you want to be able to run R but don't care about being able to install R packages that have C or C++ code.  Yeah, it could be smaller, but 250 MB ain't so bad imho -- e.g. the tidyverse image jumps to 650 MB just by adding "a few" commonly used packages.  The geospatial image is a whopping 1.3 GB -- and an image with machine learning libraries for stuff like the `keras` package is much larger still.  Maybe you could elaborate on what you mean by "large"?  

One big `RUN` is in fact required when using the strategy of deleting BUILDDEPS (in modern Docker you can do staged builds, but not afaik with Docker Hub), otherwise deleted packages are still present on the earlier layer.  We do also tend to minimize number of layers consistent with Dockerfile best practice, though that's not so important as it was when the total number of layers was more tightly capped in early days of the Rocker project.  

HTH

**Comment by eddelbuettel** [comment]
Also note that the somewhat minimal-yet-extensible rocker/r-base aka r-base comes in at around 700mb. So functionality simply has a footprint.  

But constrast for example with jupyter/scipy-notebook which I have checked out to test something else and it is 4.5gb.
